export const configureRoutes = (
  app,
  { productosController, pedidosController, notificacionesController, usuariosController }
) => {
  //PEDIDOS
  app.post(
    "/api/pedidos",
    pedidosController.crearPedido.bind(pedidosController)
  );
  app.patch(
    "/api/pedidos/:id",
    pedidosController.cancelarPedido.bind(pedidosController)
  );
  app.get(
    "/api/pedidos/",
    pedidosController.verPedidos.bind(pedidosController)
  );
  app.patch(
    "/api/pedidos/:pedidoId/items/:itemId",
    pedidosController.modificarItemPedido.bind(pedidosController)
  );
  //PRODUCTOS
  app.post(
    "/api/productos",
    productosController.crearProducto.bind(productosController)
  );
  app.get(
    "/api/productos",
    productosController.obtenerTodosLosProductos.bind(productosController)
  );
  app.get(
    "/api/productos/:id",
    productosController.obtenerProductoPorId.bind(productosController)
  );
  //VENDEDOR
  app.get(
    "/api/productos/vendedor/:idVendedor",
    productosController.obtenerProductosPorVendedor.bind(productosController)
  );
  //USUARIOS
  app.post(
    "/api/usuarios",
    usuariosController.crearUsuario.bind(usuariosController)
  );
  app.get(
    "/api/usuarios",
    usuariosController.obtenerTodosLosUsuarios.bind(usuariosController)
  );
  app.get(
    "/api/usuarios/:id",
    usuariosController.obtenerUsuarioPorId.bind(usuariosController)
  );
  app.get(
    "/api/usuarios/email/:email",
    usuariosController.obtenerUsuarioIdPorMail.bind(usuariosController)
  );
  //NOTIFICACIONES
  app.get(
    "/api/usuario/:usuarioId/notificaciones/",
    notificacionesController.obtenerNotificaciones.bind(
      notificacionesController
    )
  );
  app.patch(
    "/api/usuario/:usuarioId/notificaciones/:notificacionId",
    notificacionesController.marcarNotificacionComoLeida.bind(
      notificacionesController
    )
  );
  app.get(
    "/api/notificaciones",
    notificacionesController.obtenerTodasLasNotificaciones.bind(
      notificacionesController
    )
  );
};
